# This is a config for E2B sandbox template.
# You can use template ID (rvctg4vx9tplyc7gqjwx) or template name (webly-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("webly-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("webly-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('webly-nextjs-test')

team_id = "164b9653-714b-4ffc-aca2-8d388b120ed8"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "webly-nextjs-test"
template_id = "rvctg4vx9tplyc7gqjwx"
